// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWEohZwOT8Li2wkOsvav2yAIhwoCc_k4',
    appId: '1:460220021640:web:5fa915fb745a739a1f583d',
    messagingSenderId: '460220021640',
    projectId: 'api-yahahmd',
    authDomain: 'api-yahahmd.firebaseapp.com',
    databaseURL: 'https://api-yahahmd-default-rtdb.firebaseio.com',
    storageBucket: 'api-yahahmd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMsLRm-AjIpGi9FRVVheXUkkk3vb5HS8',
    appId: '1:460220021640:android:46e322fb9527464b1f583d',
    messagingSenderId: '460220021640',
    projectId: 'api-yahahmd',
    databaseURL: 'https://api-yahahmd-default-rtdb.firebaseio.com',
    storageBucket: 'api-yahahmd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYWEohZwOT8Li2wkOsvav2yAIhwoCc_k4',
    appId: '1:460220021640:web:40438668bb0a46eb1f583d',
    messagingSenderId: '460220021640',
    projectId: 'api-yahahmd',
    authDomain: 'api-yahahmd.firebaseapp.com',
    databaseURL: 'https://api-yahahmd-default-rtdb.firebaseio.com',
    storageBucket: 'api-yahahmd.firebasestorage.app',
  );
}
