name: petcare
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  http: ^1.2.0
  intl: ^0.18.1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.0
  image_picker: ^1.1.2
  geolocator: ^11.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  geocoding: ^3.0.0
  lottie: ^3.3.1
  shared_preferences: ^2.2.2
  saver_gallery: ^4.0.1
  path: ^1.8.3
  supabase_flutter: ^2.9.1
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.2
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins-Regular.ttf
        - asset: lib/fonts/Poppins-Bold.ttf
  assets:
    - lib/images/
